# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad3c211063ddea99325ac4ddedc9fe04dd5a8217b9e01a39721b18987375a575a7517597e85395d8dc847834959695c32e8735fc897505cd8b8a17b807600977

test:
  secret_key_base: d82fd44f7feff6292b868ca74198b9b94224478dba7130d505d6fe87af0f877391fd20eebb1e00d8eed89dd9fd7e511c62b52f0ceeea554ecababb5aea5b94c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
